export const fruitsData = [
  {
    id: 0,
    fruitsName: "Peach",
    color: "Pink",
    img: `${process.env.PUBLIC_URL}/fruits/category_tn_190.jpeg`,
    text: "山梨県で多く取れます",
    alt: "Peach",
  },
  {
    id: 1,
    fruitsName: "Cherry",
    color: "Red",
    img: `${process.env.PUBLIC_URL}/fruits/category_tn_192.jpeg`,
    text: "山形県で多く取れます",
    alt: "Cherry",
  },
  {
    id: 2,
    fruitsName: "Apple",
    color: "Red",
    img: `${process.env.PUBLIC_URL}/fruits/category_tn_193.jpeg`,
    text: "青森県で多く取れます",
    alt: "Apple",
  },
  {
    id: 3,
    fruitsName: "Grape",
    color: "Purple",
    img: `${process.env.PUBLIC_URL}/fruits/category_tn_195.jpeg`,
    text: "山梨で多く取れます",
    alt: "Grape",
  },
  {
    id: 4,
    fruitsName: "Banana",
    color: "Yellow",
    img: `${process.env.PUBLIC_URL}/fruits/category_tn_197.jpeg`,
    text: "朝食にぴったりです",
    alt: "Banana",
  },
];
